# Site settings
title: Capacity Building For India 
description: > # this means to ignore newlines until "baseurl:"
    Addressing the source of the problems of excessive migration to cities, education poverty and jobs in India and else where
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://helloravi.com" # the base hostname & protocol for your site
twitter_username: helloravikanth
github_username:  helloravi

# Build settings
markdown: kramdown
# Disqus post comments
disqus_shortname: helloravi
